Repository schubergphilis/terraform-aws-mcaf-oidc, pull requests merged in 2025-04, with the labels that each got.

#5 feature: Dynamic condition sub/aud
  README.md
  main.tf
  variables.tf
Labels: feature

#6 bug: remove unused name in the oidc_provider variable
  README.md
  examples/custom/main.tf
  modules/github/README.md
  modules/github/variables.tf
  modules/gitlab/README.md
  modules/gitlab/variables.tf
  variables.tf
Labels: bug

#7 fix: client_ids and thumbprint_url are only needed when the oidc provider is created
  README.md
  examples/custom/terraform.tf
  examples/github/terraform.tf
  examples/gitlab/terraform.tf
  main.tf
  modules/github/README.md
  modules/github/terraform.tf
  modules/gitlab/README.md
  modules/gitlab/terraform.tf
  moved.tf
  terraform.tf
  variables.tf
Labels: bug, feature

#10 bug: Correct optional setting for thumbprint_url
  main.tf
Labels: bug

#11 feature: add an additional allow_all subject filter to the github oidc module
  modules/github/README.md
  modules/github/main.tf
  modules/github/variables.tf
Labels: feature
